# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FloodTool2
                                 A QGIS plugin
 MyCoast FloodTool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-02-27
        copyright            : (C) 2019 by Meteogalicia
        email                : pablo.enrique.carracedo.garcia@xunta.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FloodTool2 class from file FloodTool2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .flood_tool2 import FloodTool2
    return FloodTool2(iface)
