# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flood_tool2_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FloodTool2DockWidgetBase(object):
    def setupUi(self, FloodTool2DockWidgetBase):
        FloodTool2DockWidgetBase.setObjectName("FloodTool2DockWidgetBase")
        FloodTool2DockWidgetBase.resize(507, 642)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        FloodTool2DockWidgetBase.setFont(font)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/plugins/flood_tool2/logo.png"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.Layers = QtWidgets.QWidget()
        self.Layers.setObjectName("Layers")
        self.run_button = QtWidgets.QPushButton(self.Layers)
        self.run_button.setGeometry(QtCore.QRect(200, 420, 89, 25))
        self.run_button.setObjectName("run_button")
        self.results_textBrowser = QtWidgets.QTextBrowser(self.Layers)
        self.results_textBrowser.setGeometry(QtCore.QRect(7, 150, 471, 211))
        self.results_textBrowser.setObjectName("results_textBrowser")
        self.progressBar = QtWidgets.QProgressBar(self.Layers)
        self.progressBar.setGeometry(QtCore.QRect(15, 370, 451, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.groupBox_time = QtWidgets.QGroupBox(self.Layers)
        self.groupBox_time.setGeometry(QtCore.QRect(20, 10, 201, 121))
        self.groupBox_time.setCheckable(False)
        self.groupBox_time.setObjectName("groupBox_time")
        self.radioButton_max = QtWidgets.QRadioButton(self.groupBox_time)
        self.radioButton_max.setGeometry(QtCore.QRect(20, 40, 112, 23))
        self.radioButton_max.setChecked(True)
        self.radioButton_max.setObjectName("radioButton_max")
        self.radioButton_timeserie = QtWidgets.QRadioButton(self.groupBox_time)
        self.radioButton_timeserie.setGeometry(QtCore.QRect(20, 80, 112, 23))
        self.radioButton_timeserie.setObjectName("radioButton_timeserie")
        self.groupBox_codes = QtWidgets.QGroupBox(self.Layers)
        self.groupBox_codes.setGeometry(QtCore.QRect(250, 10, 211, 121))
        self.groupBox_codes.setObjectName("groupBox_codes")
        self.radioButton_light = QtWidgets.QRadioButton(self.groupBox_codes)
        self.radioButton_light.setGeometry(QtCore.QRect(20, 80, 171, 23))
        self.radioButton_light.setObjectName("radioButton_light")
        self.radioButton_level = QtWidgets.QRadioButton(self.groupBox_codes)
        self.radioButton_level.setGeometry(QtCore.QRect(20, 40, 161, 23))
        self.radioButton_level.setChecked(True)
        self.radioButton_level.setObjectName("radioButton_level")
        self.tabWidget.addTab(self.Layers, "")
        self.hydrodynamic = QtWidgets.QWidget()
        self.hydrodynamic.setObjectName("hydrodynamic")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.hydrodynamic)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(14, 10, 461, 118))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.hydro_formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.hydro_formLayout.setContentsMargins(0, 0, 0, 0)
        self.hydro_formLayout.setObjectName("hydro_formLayout")
        self.hydro_thredds_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.hydro_thredds_label.setObjectName("hydro_thredds_label")
        self.hydro_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.hydro_thredds_label)
        self.hydro_field_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.hydro_field_label.setObjectName("hydro_field_label")
        self.hydro_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.hydro_field_label)
        self.hydro_field_comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.hydro_field_comboBox.setObjectName("hydro_field_comboBox")
        self.hydro_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hydro_field_comboBox)
        self.hydro_grid_comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.hydro_grid_comboBox.setObjectName("hydro_grid_comboBox")
        self.hydro_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hydro_grid_comboBox)
        self.hydro_variable_comboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.hydro_variable_comboBox.setEnabled(True)
        self.hydro_variable_comboBox.setObjectName("hydro_variable_comboBox")
        self.hydro_formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.hydro_variable_comboBox)
        self.hydro_variable_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.hydro_variable_label.setObjectName("hydro_variable_label")
        self.hydro_formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.hydro_variable_label)
        self.tideSolution_checkBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.tideSolution_checkBox.setObjectName("tideSolution_checkBox")
        self.hydro_formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tideSolution_checkBox)
        self.hydro_calendarWidget = QtWidgets.QCalendarWidget(self.hydrodynamic)
        self.hydro_calendarWidget.setEnabled(True)
        self.hydro_calendarWidget.setGeometry(QtCore.QRect(18, 170, 456, 171))
        self.hydro_calendarWidget.setObjectName("hydro_calendarWidget")
        self.label_available_hydro = QtWidgets.QLabel(self.hydrodynamic)
        self.label_available_hydro.setGeometry(QtCore.QRect(20, 140, 111, 17))
        self.label_available_hydro.setObjectName("label_available_hydro")
        self.tabWidget.addTab(self.hydrodynamic, "")
        self.wave = QtWidgets.QWidget()
        self.wave.setObjectName("wave")
        self.formLayoutWidget = QtWidgets.QWidget(self.wave)
        self.formLayoutWidget.setGeometry(QtCore.QRect(13, 14, 461, 89))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.wave_formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.wave_formLayout.setContentsMargins(0, 0, 0, 0)
        self.wave_formLayout.setObjectName("wave_formLayout")
        self.wave_thredds_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.wave_thredds_label.setObjectName("wave_thredds_label")
        self.wave_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.wave_thredds_label)
        self.wave_field_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.wave_field_label.setObjectName("wave_field_label")
        self.wave_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.wave_field_label)
        self.wave_field_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.wave_field_comboBox.setObjectName("wave_field_comboBox")
        self.wave_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.wave_field_comboBox)
        self.wave_variable_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.wave_variable_label.setObjectName("wave_variable_label")
        self.wave_formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.wave_variable_label)
        self.wave_variable_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.wave_variable_comboBox.setObjectName("wave_variable_comboBox")
        self.wave_formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.wave_variable_comboBox)
        self.wave_grid_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.wave_grid_comboBox.setObjectName("wave_grid_comboBox")
        self.wave_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.wave_grid_comboBox)
        self.wave_calendarWidget = QtWidgets.QCalendarWidget(self.wave)
        self.wave_calendarWidget.setEnabled(True)
        self.wave_calendarWidget.setGeometry(QtCore.QRect(18, 170, 456, 171))
        self.wave_calendarWidget.setObjectName("wave_calendarWidget")
        self.label_available_wave = QtWidgets.QLabel(self.wave)
        self.label_available_wave.setGeometry(QtCore.QRect(20, 140, 111, 17))
        self.label_available_wave.setObjectName("label_available_wave")
        self.tabWidget.addTab(self.wave, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        FloodTool2DockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(FloodTool2DockWidgetBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FloodTool2DockWidgetBase)

    def retranslateUi(self, FloodTool2DockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        FloodTool2DockWidgetBase.setWindowTitle(_translate("FloodTool2DockWidgetBase", "FloodTool2"))
        self.run_button.setText(_translate("FloodTool2DockWidgetBase", "Run"))
        self.groupBox_time.setTitle(_translate("FloodTool2DockWidgetBase", "Time control"))
        self.radioButton_max.setText(_translate("FloodTool2DockWidgetBase", "Max level"))
        self.radioButton_timeserie.setText(_translate("FloodTool2DockWidgetBase", "Timeseries"))
        self.groupBox_codes.setTitle(_translate("FloodTool2DockWidgetBase", "Output categorization"))
        self.radioButton_light.setText(_translate("FloodTool2DockWidgetBase", "Compute color codes"))
        self.radioButton_level.setText(_translate("FloodTool2DockWidgetBase", "Compute real level"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Layers), _translate("FloodTool2DockWidgetBase", "Layers"))
        self.hydro_thredds_label.setText(_translate("FloodTool2DockWidgetBase", "Model grid:"))
        self.hydro_field_label.setText(_translate("FloodTool2DockWidgetBase", "Layer field:"))
        self.hydro_variable_label.setText(_translate("FloodTool2DockWidgetBase", "Variable:"))
        self.tideSolution_checkBox.setText(_translate("FloodTool2DockWidgetBase", "Use tide solution "))
        self.label_available_hydro.setText(_translate("FloodTool2DockWidgetBase", "Available files:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.hydrodynamic), _translate("FloodTool2DockWidgetBase", "Hydrodynamic"))
        self.wave_thredds_label.setText(_translate("FloodTool2DockWidgetBase", "Model grid:"))
        self.wave_field_label.setText(_translate("FloodTool2DockWidgetBase", "Layer field:"))
        self.wave_variable_label.setText(_translate("FloodTool2DockWidgetBase", "Variable:"))
        self.label_available_wave.setText(_translate("FloodTool2DockWidgetBase", "Available files:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wave), _translate("FloodTool2DockWidgetBase", "Wave"))

from . import resources
